toolbar:
  - insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
  - print preview media | forecolor backcolor emoticons | fontselect fontsizeselect
plugins:
  - image
  - link
  - advlist 
  - autolink 
  - lists 
  - charmap 
  - print 
  - preview 
  - hr 
  - anchor 
  - pagebreak
  - searchreplace 
  - wordcount 
  - visualblocks 
  - visualchars 
  - code 
  - fullscreen
  - insertdatetime 
  - media 
  - nonbreaking 
  - save 
  - table 
  - contextmenu 
  - directionality
  - emoticons 
  - template 
  - paste 
  - textcolor 
  - colorpicker 
  - textpattern 
  - imagetools
fontsize_formats:
  - 6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 24pt 36pt 48pt
skin: 'oxide-dark'
content_css: 'content.css'
extended_valid_elements: 'script[language|type|src],style[type],a-scene,a-text,a-camera'
custom_elements: 'a-scene,a-text,a-camera'
valid_children: '+body[style]'
images_upload_url: '/tinymce_assets' # for automatic_uploads
images_upload_credentials: true # sends session information with the upload